### ISSUE TITLE
Please support creating temporary directories with mode 0700

### ISSUE THREAD

**Issue by joshtriplett** [Stebalien/tempfile#114]
tempfile creates temporary files with mode 0600, but doesn't seem to restrict permissions on temporary directories at all. I'd like to create a temporary directory with mode 0700 (and not rely on the current umask to restrict write access). Ideally, I'd like tempfile to do so by default, for security reasons; if there's some reason the default permissions can't change, then I'd like to have an option to set them.

**Comment by Stebalien** [comment]
See https://github.com/Stebalien/tempfile/pull/61. Basically: needs implementation.

**Comment by lucab** [comment]
I also have a usecase where explicitly setting the permission mask (`0664` in my case) without relying on the default umask would be helpful.
I think that having a new setter method on the builder, taking a proper `Pemissions` argument,  would be great.
#61 is not currently going in that direction due to shortcomings on non-Linux platforms.

**Comment by Stebalien** [comment]
Implemented.
