### ISSUE TITLE
Provide a way to convert a TempFile into a regular named file (via hard links)

### ISSUE THREAD

**Issue by jmesmon** [Stebalien/tempfile#13]
May need to have the availability of this interface be os dependent, not sure it jives with how windows works.

**Comment by Stebalien** [comment]
The issue is FreeBSD/OSX. On windows, you can't have unlinked/deleted temporary files (but you can set a delete on close flag) so all I have to do is rename the file. However, on *nix OSs, I either immediately unlink the temporary file or open it with `O_TMPFILE` (linux). On linux, I can then link it into the filesystem using linkat and proc. However, this doesn't work on any of the other *nix operating systems.

In general, I don't want add platform specific APIs (especially core ones like persist). This is supposed to be a cross-platform library and I'd rather not provide any compatibility footguns. Instead, I'd like to make `NamedTempFile` more secure:

1. Automatically create a directory owned by the current user under the default temporary directory iff the default temporary directory is not owned by the current user.
2. Keep an open file descriptor to this directory around (maybe even cache it somewhere global) and perform all operations relative to this file descriptor.

However, before I do this, I'd kind of like to make working with directories less painful (implement a Directory type similar to the File type).

**Comment by Stebalien** [comment]
Given that `TempFile` no longer exists and that we now use normal `File` objects for temporary files, this isn't possible (literally, no place to put the method).

**Comment by g2p** [comment]
Not sure if I should create a new issue, but couldn't NamedTempFile::persist be made secure on Linux using linkat?

I would then use it to atomically create files with known contents: create a NamedTempFile under the application data directory, write to it, and persist it under a well known path.

**Comment by Stebalien** [comment]
So, that would only be secure *if* the user controls the parent directory. My suggestion above was to *create* this parent directory.

However, this might be considered a breaking change at this point so I'd probably have to add it as an option. Also, it unfortunately keeps an additional file descriptor open which could be expensive in some cases.
