### ISSUE TITLE
Maybe setting the permissions of the temporary file is a misfeature?

### ISSUE THREAD

**Issue by grahamc** [Stebalien/tempfile#193]
Today, tempfile sets the permissions to 0600. When the file is persisted, this mode is then propagated. Unfortunately 0600 isn't a universally applicable mode, especially in cases where the temporary file is being shared with peers on the machine. This is kind-of-but-not-really easy to remedy: programs can chmod the file as they wish.

However, I think it is a mistake to set the mode by default at all.

In order for a program to obey the configured umask, the Rust program has to either parse `/proc/self/status` for the umask, or set / reset the current program's umask. This second option isn't thread safe, and the first option is a bit yucky too. The program then has to apply the umask and calculate the appropriate bits to chmod the file. There could of course be an error in the duration, leaving a file with an improper mode.

One reason this is such a pain is when libraries I don't necessarily control use and persist a NamedTemporaryFile. Should the libraries do the umask dance? I don't think so: it isn't safe for them to set/reset the umask since they don't know if they're in a multi-threaded environment. I'd rather them not depend on `/proc` either, since I'd like to use them in environments without `/proc` if possible.

I've seen various pull requests and issues about this option: approximately a third of the open issues are related to this. I think those options are okay, but what I would really like to see is a function that makes no statements about mode at all and defers to the operating environment of the program:

```rust
pub fn create_named_from_umask(path: &Path, open_options: &mut OpenOptions) -> io::Result<File> {
    open_options.read(true).write(true).create_new(true);

    open_options.open(path)
}
```

Is this something that would be interesting?

**Comment by lheckemann** [comment]
>In order for a program to obey the configured umask, the Rust program has to either parse /proc/self/status for the umask, or set / reset the current program's umask.

This isn't quite correct -- the umask is _always_ obeyed, being applied to the mode by the kernel when the `open` syscall (or variant thereof) happens.

Given the combination of these unfortunate circumstances:
- Many systems have a shared, world-readable temporary directory, so 600 is a sensible default for temporary files
- umask is all that prevents world-readability in many scenarios, since pretty much the whole world including [Rust's stdlib](https://doc.rust-lang.org/std/os/unix/fs/trait.OpenOptionsExt.html#tymethod.mode), GNU coreutils and various `libc`s (implementing `fopen(3)`) default to `666` --- so changing umask to be less restrictive is very risky (the caller of the program can't specify _which_ files it wants to have more open permissions on, and the program itself can only change `umask` safely if it's single-threaded)
- The default of 0666 limits the executable bit, so an unspecified mode would _still_ not completely defer to the operating environment
- And finally, Rust's stdlib doesn't allow tempfile to determine whether the caller has already set a different mode when the variant accepting an `OpenOptions` is used (which would be a nice way to defer this decision to the caller while setting a sensible default)

I think the best way forwards is to continue setting the mode to 600, but to add a variant of the function that allows passing an explicit mode which overrides the safe default -- but not one that leaves the mode completely alone.

And I'd say the answer whenever you want things to be writable by anyone other than the user is not doing anything involving the umask (because of its non-specificity), but using chmod -- which is completely explicit about the desired mode and specific to the desired file.

**Comment by lolbinarycat** [comment]
changing the default behavior could have significant security repercussions for anything that relies on the current behavior to hide secrets.

**Comment by lheckemann** [comment]
@lolbinarycat so you agree with this?

>I think the best way forwards is to continue setting the mode to 600, but to add a variant of the function that allows passing an explicit mode which overrides the safe default -- but not one that leaves the mode completely alone.

**Comment by Stebalien** [comment]
We can now set default permissions (`Builder::permissions`), so I'll consider this fixed (as much as possible, anyways).
