### ISSUE TITLE
Provide easy way to get Path of the tempfile.

### ISSUE THREAD

**Issue by lunemec** [Stebalien/tempfile#27]
Hello,
I'd llike to get the Path of the created temporary file. I'm new to Rust, but from what I saw in the docs and in the code of std:fs:File, there is no way to get Path of the open File (this would be nice addition to std, I'll post it on rust reddit for feedback), but in the meantime, it would be nice if you'd return some struct containing the tmpfile's Path and File.

I looked into the internal impl of sys::File, where in fmt::Debug for File there are get_path implementations, but they use the file descriptor to re-read the file path, which is strange, since the File object should have this information :)

Thx.

**Comment by Stebalien** [comment]
You're looking for [NamedTempFile](https://stebalien.github.io/tempfile/tempfile/struct.NamedTempFile.html). The `File` returned by `tempfile()` and `tempfile_in(dir)` isn't guaranteed to even have a path (it doesn't have one on unix like operating systems).

In general, there's no way to get the path of a `File` because not all files have paths. For example, on Linux, you can open a file, "delete" it, and then continue to read and write to the file as normal. I say "delete" in quotes because you're actually unlinking it from the filesystem, not deleting it. It won't actually be deleted until it has been closed.
