### ISSUE TITLE
(Question) How can I read/write with different file handles from/to the same tempfile?

### ISSUE THREAD

**Issue by brglng** [Stebalien/tempfile#50]
Hello,

I tried the following code:

```rust
let f = tempfile()?;
let writer = BufWriter::new(f.try_clone()?);
let reader = BufReader::new(f.try_clone()?);
```

But this does not work, because writer and reader share the same file, and the reader cannot read any data since the writer moves the file's internal pointer to the end. What I want is to read/write the same file like a queue.

Thanks!

**Comment by Stebalien** [comment]
Unfortunately, this is impossible with `tempfile()` due to limitations on MacOS/FreeBSD (it's possible on Windows and usually possible on Linux).

However, you *can* get multiple handles for a `NamedTempFile` by calling the `reopen()` method. After reopening it, you can drop the original named tempfile to effectively "demote" the it to an unnamed temporary file. This won't close the reopened copies but will ensure that the that the temporary file will get cleaned up by the OS even if your application crashes.

```rust
let f = NamedTempFile::new()?;
let writer = BufWriter::new(f.reopen()?);
let reader = BufReader::new(f.reopen()?);
drop(f);
```

**Comment by brglng** [comment]
Thank you! That exactly solves my problem.

**Comment by brglng** [comment]
Hi @Stebalien , can I do the same thing with `SpooledTempFile`?

**Comment by Stebalien** [comment]
Unfortunately, no:

1. When in-memory, you'd need thread safety (so we'd need to introduce a thread-safe spool file).
2. When "rolled" to disk, `SpooledTempFile` is unnamed (created with `tempfile()`).

**Comment by brglng** [comment]
Thanks for your answer. Maybe I have to look for some other approaches.
